# Generated by Django 3.1.2 on 2022-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0002_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(db_index=True, editable=False, max_length=100),
        ),
    ]
