# Generated by Django 3.1.2 on 2022-03-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0003_auto_20220301_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(db_index=True, max_length=1000, unique=True),
        ),
    ]
