# Generated by Django 3.1.2 on 2022-03-01 12:05

from django.db import migrations, models
import url_shortening.models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0004_auto_20220301_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default=url_shortening.models._generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='URL ID'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(db_index=True, max_length=100),
        ),
    ]
